version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-alpine
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t shityimage .
  deploy:
    docker:
      - image: circleci/openjdk:17-jdk-alpine
    steps:
      - checkout
      - run:
          name: Deploy to AWS EC2
          command: |
            # Replace with your AWS CLI commands to deploy the Docker image to EC2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: development
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master